stages:
  - build
  - release

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "tcp://docker:2375"
  GIT_STRATEGY: fetch
  GET_SOURCES_ATTEMPTS: "3"

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  except:
  - tags
  image: docker:stable
  script:
  - docker build --pull -t $CI_REGISTRY_IMAGE:latest .
  - docker push $CI_REGISTRY_IMAGE
  services:
  - docker:dind
  stage: build

release:
  image: docker:stable
  only:
  - tags
  script:
  - docker build --pull -t $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
  - docker push $CI_REGISTRY_IMAGE
  services:
  - docker:dind
  stage: release
